# Generated by Django 4.2.25 on 2025-10-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_digest",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 digest of email for lookups",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="encrypted_email",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
