# Generated by Django 4.2.25 on 2025-10-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("signup", "Sign up"), ("login", "Login")],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("username_submitted", models.CharField(blank=True, max_length=150)),
                (
                    "email_digest",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("successful", models.BooleanField(default=False)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authentication_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "ip_address", "created_at"],
                        name="accounts_au_event_t_f27035_idx",
                    )
                ],
            },
        ),
    ]