# Generated by Django 4.2.27 on 2025-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("gcash", "GCash"),
                    ("paymaya", "PayMaya"),
                    ("grab_pay", "GrabPay"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Payment Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
